version: "3.9"
services:
  workout-frontend:
    restart: always
    image: workout/frontend:latest
    hostname: workout-frontend
    container_name: workout-frontend
    networks:
      - external-net
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: workout
networks:
  external-net:
    external:
      name: external-net
