version: "3.9"
services:
  workout-frontend:
    restart: always
    image: workout/frontend:latest
    hostname: workout-frontend
    container_name: workout-frontend
    networks:
      - external-net
    ports:
      - "3000:80"
networks:
  external-net:
    name: external-net
    external: true