version: "3.9"
services:
  babymed-frontend:
    restart: always
    image: babymed/frontend:latest
    hostname: babymed-frontend
    container_name: babymed-frontend
    networks:
      - external-net
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: babymed
networks:
  external-net:
    external:
      name: external-net
